"""Locust load test for PostgreSQL-backed atomic DAG task claims.

The database is prepared before users are spawned, so schema creation and the
initial bulk seed are not included in the request latency measurements.
"""

from __future__ import annotations

import os
import socket
import time
import uuid
from contextlib import contextmanager

import gevent
from locust import User, between, events, task
from locust.runners import MasterRunner
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from lib.dag_scheduler import CLAIM_NEXT_TASK_SQL, CREATE_DAG_TABLES_SQL
from lib.db import get_pool_config, get_postgres_uri


RUN_ID = os.getenv("LOAD_RUN_ID", f"load-run-{int(time.time())}")
THREAD_ID = os.getenv("LOAD_THREAD_ID", RUN_ID)
SEED_TASKS = int(os.getenv("LOAD_SEED_TASKS", "1000000"))
REFILL_TASKS = os.getenv("LOAD_REFILL_TASKS", "true").lower() in {"1", "true", "yes", "on"}
REFILL_THRESHOLD = int(os.getenv("LOAD_REFILL_THRESHOLD", "200000"))
REFILL_BATCH = int(os.getenv("LOAD_REFILL_BATCH", "200000"))
REFILL_INTERVAL = float(os.getenv("LOAD_REFILL_INTERVAL", "5"))

_pool: ConnectionPool | None = None
_refill_greenlet = None
_stopping = False


def _validate_settings() -> None:
    values = {
        "LOAD_SEED_TASKS": SEED_TASKS,
        "LOAD_REFILL_THRESHOLD": REFILL_THRESHOLD,
        "LOAD_REFILL_BATCH": REFILL_BATCH,
    }
    for name, value in values.items():
        if value < 0:
            raise ValueError(f"{name} must be >= 0")
    if REFILL_TASKS and REFILL_BATCH == 0:
        raise ValueError("LOAD_REFILL_BATCH must be > 0 when refilling is enabled")
    if REFILL_INTERVAL <= 0:
        raise ValueError("LOAD_REFILL_INTERVAL must be > 0")


def _create_pool() -> ConnectionPool:
    config = get_pool_config("LOAD_POSTGRES_POOL")
    return ConnectionPool(
        get_postgres_uri(),
        min_size=config.min_size,
        max_size=config.max_size,
        timeout=config.timeout,
        max_waiting=config.max_waiting,
        kwargs={"autocommit": True, "row_factory": dict_row},
        open=False,
        name=f"dag-load-{os.getpid()}",
    )


@contextmanager
def _run_lock(conn):
    """Serialize seed/refill work across Locust worker processes."""
    conn.execute("SELECT pg_advisory_lock(hashtextextended(%s, 0))", (RUN_ID,))
    try:
        yield
    finally:
        conn.execute("SELECT pg_advisory_unlock(hashtextextended(%s, 0))", (RUN_ID,))


def _insert_tasks(conn, first: int, last: int, id_prefix: str = RUN_ID) -> int:
    if last < first:
        return 0
    cursor = conn.execute(
        """
        INSERT INTO tasks (
            id, subject, description, thread_id, owner, status,
            blocked_by_count, metadata, updated_at
        )
        SELECT
            %s || '-task-' || n,
            'load task ' || n,
            'generated by the DAG claim load test',
            %s,
            NULL,
            'pending',
            0,
            jsonb_build_object('priority', 5, 'load_run_id', %s::text),
            NOW()
        FROM generate_series(%s::bigint, %s::bigint) AS n
        ON CONFLICT (id) DO NOTHING
        """,
        (id_prefix, THREAD_ID, RUN_ID, first, last),
    )
    return cursor.rowcount


def _prepare_database() -> None:
    assert _pool is not None
    with _pool.connection() as conn, _run_lock(conn):
        conn.execute(CREATE_DAG_TABLES_SQL)
        row = conn.execute(
            "SELECT count(*) AS total FROM tasks WHERE thread_id = %s",
            (THREAD_ID,),
        ).fetchone()
        existing = row["total"]
        inserted = _insert_tasks(conn, existing + 1, SEED_TASKS)
        print(
            f"[dag-load] run={RUN_ID} thread={THREAD_ID} "
            f"existing={existing} inserted={inserted} target={SEED_TASKS}",
            flush=True,
        )


def _refill_once() -> int:
    assert _pool is not None
    with _pool.connection() as conn, _run_lock(conn):
        if REFILL_THRESHOLD == 0:
            return 0
        enough_tasks = conn.execute(
            """
            SELECT EXISTS (
                SELECT 1
                FROM tasks
                WHERE thread_id = %s
                  AND status = 'pending'
                  AND blocked_by_count = 0
                OFFSET %s LIMIT 1
            ) AS enough
            """,
            (THREAD_ID, REFILL_THRESHOLD - 1),
        ).fetchone()["enough"]
        if enough_tasks:
            return 0

        prefix = f"{RUN_ID}-refill-{time.time_ns()}-{os.getpid()}"
        inserted = _insert_tasks(conn, 1, REFILL_BATCH, prefix)
        print(f"[dag-load] refilled={inserted}", flush=True)
        return inserted


def _refill_loop() -> None:
    while not _stopping:
        gevent.sleep(REFILL_INTERVAL)
        if _stopping:
            return
        try:
            _refill_once()
        except Exception as exc:  # reported separately from user request metrics
            print(f"[dag-load] refill failed: {exc!r}", flush=True)


@events.test_start.add_listener
def on_test_start(environment, **_kwargs) -> None:
    global _pool, _refill_greenlet, _stopping
    if isinstance(environment.runner, MasterRunner):
        return
    _validate_settings()
    _stopping = False
    _pool = _create_pool()
    _pool.open(wait=True)
    _prepare_database()
    if REFILL_TASKS:
        _refill_greenlet = gevent.spawn(_refill_loop)


@events.test_stop.add_listener
def on_test_stop(environment, **_kwargs) -> None:
    global _refill_greenlet, _stopping
    if isinstance(environment.runner, MasterRunner):
        return
    _stopping = True
    if _refill_greenlet is not None:
        _refill_greenlet.kill(block=False)
        _refill_greenlet = None
    # Locust can interrupt greenlets while psycopg is still consuming a result.
    # Closing the pool here would race those libpq operations and produce noisy
    # "another command is already in progress" warnings. This locustfile is
    # headless/process-scoped, so the OS closes the connections on process exit.


class AtomicDAGClaimUser(User):
    """A worker that repeatedly performs the production atomic claim query."""

    wait_time = between(0.01, 0.05)

    def on_start(self) -> None:
        self.owner = f"load-{socket.gethostname()}-{os.getpid()}-{uuid.uuid4().hex}"

    @task
    def claim_next_task(self) -> None:
        started = time.perf_counter()
        error = None
        claimed = None
        try:
            if _pool is None:
                raise RuntimeError("PostgreSQL pool is not initialized")
            with _pool.connection() as conn:
                claimed = conn.execute(
                    CLAIM_NEXT_TASK_SQL,
                    (THREAD_ID, self.owner),
                ).fetchone()
            if claimed is None:
                raise RuntimeError("no ready task available")
        except Exception as exc:
            error = exc

        events.request.fire(
            request_type="PostgreSQL",
            name="atomic_claim_next_task",
            response_time=(time.perf_counter() - started) * 1000,
            response_length=1 if claimed is not None else 0,
            exception=error,
            context={"run_id": RUN_ID, "thread_id": THREAD_ID},
        )
